{{- if and .Values.cache.enabled .Values.cache.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.cache.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.cache.labels" . | nindent 4 }}
  {{- with .Values.cache.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.cache.serviceAccount.automount }}
{{- end }}
