{{- if and .Values.cache.enabled .Values.cache.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kompass-compute.cache.name" . }}
  labels:
    {{- include "kompass-compute.cache.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kompass-compute.cache.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-compute.cache.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
