{{- if .Values.hiberscaler.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kompass-compute.hiberscaler.name" . }}
  labels:
    {{- include "kompass-compute.hiberscaler.labels" . | nindent 4 }}
webhooks:
  - name: validator.kompass.zesty.co
    admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: {{ include "kompass-compute.hiberscaler.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-qscaler
    failurePolicy: Ignore
    timeoutSeconds: 2
    sideEffects: None
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "qscaler.qubex.ai"
        apiVersions:
          - v1alpha1
        resources:
          - qscalers
        scope: Cluster
  {{- end }}
