{{- if and .Values.hiberscaler.enabled .Values.hiberscaler.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kompass-compute.hiberscaler.name" . }}
  labels:
    {{- include "kompass-compute.hiberscaler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "watch"
      - "create"
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
      - "watch"
      - "create"
      - "patch"
{{- end }}
