{{- if and .Values.hiberscaler.enabled .Values.hiberscaler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.hiberscaler.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.hiberscaler.labels" . | nindent 4 }}
  {{- with .Values.hiberscaler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.hiberscaler.serviceAccount.automount }}
{{- end }}
