{{- if and .Values.hiberscaler.enabled .Values.hiberscaler.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kompass-compute.hiberscaler.name" . }}
  labels:
    {{- include "kompass-compute.hiberscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kompass-compute.hiberscaler.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-compute.hiberscaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
