{{- if .Values.hiberscaler.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kompass-compute.hiberscaler.name" . }}
  labels:
    {{- include "kompass-compute.hiberscaler.labels" . | nindent 4 }}
webhooks:
  - name: pod-assigner.kompass.zesty.co
    admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: {{ include "kompass-compute.hiberscaler.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /assign-pod-to-shard
    failurePolicy: Ignore
    timeoutSeconds: 2
    sideEffects: None
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
        scope: Namespaced
  {{- end }}
