{{- if .Values.hiberscaler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kompass-compute.hiberscaler.webhookCertSecretName" . }}
  labels:
    {{- include "kompass-compute.hiberscaler.labels" . | nindent 4 }}
{{- end }}
