{{- if and .Values.imageSizeCalculator.enabled .Values.imageSizeCalculator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kompass-compute.imageSizeCalculator.name" . }}
  labels:
    {{- include "kompass-compute.imageSizeCalculator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "nodes"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "qscaler.qubex.ai"
    resources:
      - "qcacheshards"
      - "qubexconfigs"
      - "qcachepullmappings"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "qscaler.qubex.ai"
    resources:
      - "qcacherevisioncreations"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "qscaler.qubex.ai"
    resources:
      - "qcacherevisioncreations/status"
    verbs:
      - "update"
      - "patch"
{{- end }}
