{{- if and .Values.imageSizeCalculator.enabled .Values.imageSizeCalculator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.imageSizeCalculator.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.imageSizeCalculator.labels" . | nindent 4 }}
  {{- with .Values.imageSizeCalculator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.imageSizeCalculator.serviceAccount.automount }}
{{- end }}
