{{- if and .Values.otel.enabled .Values.otel.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.otel.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.otel.labels" . | nindent 4 }}
  {{- with .Values.otel.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.otel.serviceAccount.automount }}
{{- end }}
