{{- if and .Values.snapshooter.enabled .Values.snapshooter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.snapshooter.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.snapshooter.labels" . | nindent 4 }}
  {{- with .Values.snapshooter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.snapshooter.serviceAccount.automount }}
{{- end }}
