{{- if and .Values.telemetryManager.enabled .Values.telemetryManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.telemetryManager.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.telemetryManager.labels" . | nindent 4 }}
  {{- with .Values.telemetryManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.telemetryManager.serviceAccount.automount }}
{{- end }}
