{{- if and .Values.telemetryManager.enabled .Values.telemetryManager.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kompass-compute.telemetryManager.name" . }}
  labels:
    {{- include "kompass-compute.telemetryManager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "qscaler.qubex.ai"
    resources:
      - "qscalers"
      - "qbakers"
      - "qnodes"
      - "resumetasks"
      - "qcacheshards"
      - "qubexconfigs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "kompass.zesty.co"
    resources:
      - "workloaddescriptors"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
      - "replicasets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
      - "watch"
{{- end }}
