{{- if and .Values.telemetryManager.enabled .Values.telemetryManager.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kompass-compute.telemetryManager.name" . }}
  labels:
    {{- include "kompass-compute.telemetryManager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kompass-compute.telemetryManager.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-compute.telemetryManager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
