{{- if and .Values.uninstaller.enabled .Values.uninstaller.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kompass-compute.uninstaller.name" . }}
  labels:
    {{- include "kompass-compute.uninstaller.labels" . | nindent 4 }}
  annotations:
    {{- /* This is what defines this resource as a hook. Without this line, the job is considered part of the release. */}}
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kompass-compute.uninstaller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-compute.uninstaller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
