{{- if and .Values.uninstaller.enabled .Values.uninstaller.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kompass-compute.uninstaller.name" . }}
  labels:
    {{- include "kompass-compute.uninstaller.labels" . | nindent 4 }}
  annotations:
    {{- /* This is what defines this resource as a hook. Without this line, the job is considered part of the release. */}}
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
  - apiGroups:
      - "qscaler.qubex.ai"
    resources:
      - "qubexconfigs"
      - "qscalers"
      - "qbakers"
      - "qnodes"
      - "resumetasks"
      - "qcacherevisioncreations"
      - "qcacheshards"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "create"
      - "delete"
{{- end }}
