{{- if and .Values.uninstaller.enabled .Values.uninstaller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.uninstaller.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.uninstaller.labels" . | nindent 4 }}
  annotations:
    {{- /* This is what defines this resource as a hook. Without this line, the job is considered part of the release. */}}
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.uninstaller.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.uninstaller.serviceAccount.automount }}
{{- end }}
