{{- if and .Values.vector.enabled .Values.vector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.vector.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.vector.labels" . | nindent 4 }}
  {{- with .Values.vector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.vector.serviceAccount.automount }}
{{- end }}
