{{- if and .Values.vector.enabled .Values.vector.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kompass-compute.vector.name" . }}
  labels:
    {{- include "kompass-compute.vector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kompass-compute.vector.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-compute.vector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
